server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pastebin
      username: pastebin
      password: pastebin
  thymeleaf:
    mode: LEGACYHTML5
    cache: false